# Generated by Django 4.2.28 on 2026-02-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="global_index",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="document",
            name="authors",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="document",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["global_index"], name="research_ag_global__c9b2dc_idx"
            ),
        ),
    ]
