# Generated by Django 4.2.28 on 2026-02-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_agent", "0002_chunk_global_index_document_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
